### PR TITLE
Async ads for IE 9

### PR DESCRIPTION
**Pull request by ignasigarcia**

### CODE REVIEW

**Comment by ignasigarcia** [comment]
@wtajak Here you can see the Pull Request of the code we did today. There are 2 JS files, one minified for production use and the other to keep as a reference.

We can discuss these two on Monday.

:)

**Comment by wtajak** [comment]
looks good to me :+1:

**Comment by wtajak** [comment]
btw I'm experiencing github issues in Chrome, I was not able to comment with neither wtajak or mwrwebteam account in that browser. This comment is added in Safari.
screen shot 2015-08-09 at 11 56 29

**Comment by ignasigarcia** [comment]
Thanks for checking it Wojtek :)

I can see that your comment went through so it must have been a glitch from Github.

**Pull request merged**
